# Node.js 20 버전을 사용하는 베이스 이미지 지정
FROM wotjr980321/node

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사
COPY package*.json ./

# npm을 이용해 패키지 설치
RUN npm install

# 나머지 소스 파일 복사
COPY . .

# 앱 실행을 위한 포트 지정
EXPOSE 3000

# 애플리케이션 실행
CMD ["npm", "start"]
