FROM node:20
# 경로 설정하기
# package.json 워킹 디렉토리에 복사 (.은 설정한 워킹 디렉토리를 뜻함)
# WORKDIR /react_admin


WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json .
# 명령어 실행 (의존성 설치)
RUN npm install
# RUN npm install -g react-scripts

COPY . .

# RUN npm run build

# 3000번 포트 노출
EXPOSE 8000

# npm start 스크립트 실행
CMD ["npm", "start"]

# 그리고 Dockerfile로 docker 이미지를 빌드해야한다.
# $ docker build .